### PR TITLE
Technical Service XML retrieval + formatting + code cleaning

### PR DESCRIPTION
**Pull request by GoebelL**
**Changes in this Pull Request:**
- Reimplemented GET endpoints to retrieve technical services templates as XML (embedded in JSON)

**Mandatory checks:**
- [X] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [X] changes were tested manually
- [X] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
Tbd

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/269)

### CODE REVIEW

**Comment by farmakiG** [comment]
*[`oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceBackend.java` line 72 at r1](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/269#-N8hUqyB13BvQFfC6Q9T:-N8hUqyB13BvQFfC6Q9U:bpsk05c) ([raw file](https://github.com/servicecatalog/oscm-rest-api/blob/70c35e2c5af6a49b5ce2646688f893da680f5c1d/oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceBackend.java#L72)):*
> ```Java
>   public RestBackend.Get<TechnicalServiceXMLRepresentation, ServiceParameters> getXML() {
>     return params -> {
>       List<VOTechnicalService> ts =
> ```

Where is the exception handling? (e.g. OperationNotPermittedException)

**Review by farmakiG — COMMENTED** [review]
> Reviewed 5 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/269)* status: 5 of 16 files reviewed, 1 unresolved discussion (waiting on @farmakiG and @GoebelL)

**Review by farmakiG — COMMENTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/269)* status: 6 of 16 files reviewed, all discussions resolved (waiting on @farmakiG)

**Review by farmakiG — APPROVED** [review]
:lgtm:

> Reviewed 9 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/269#-:-N8hz1kN0q5HlVAR_UDP:bnfp4nl)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @farmakiG)

**Review by farmakiG — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/269#-:-N8hzdnZ3JjYbn6dAjMf:bnfp4nl)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @farmakiG)

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/269)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @farmakiG)

___
*[`oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceBackend.java` line 72 at r1](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/269#-N8hUqyB13BvQFfC6Q9T:-N8i1emBBLiQbE5c7tYO:bba6pva) ([raw file](https://github.com/servicecatalog/oscm-rest-api/blob/70c35e2c5af6a49b5ce2646688f893da680f5c1d/oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceBackend.java#L72)):*
<details><summary><i>Previously, farmakiG wrote…</i></summary><blockquote>

Where is the exception handling? (e.g. OperationNotPermittedException)
</blockquote></details>

The getXML method only returns a functional interface. This cannot throw actually. The exception can rise only where the returned function is executed.
This is here in [RestResource.get()](https://github.com/servicecatalog/oscm-rest-api/blob/getTechServicesAsXML/oscm-rest-api-common/src/main/java/org/oscm/rest/common/RestResource.java#L63)

**Review by farmakiG — APPROVED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GoebelL)

**Pull request merged**
