### PR TITLE
add get xml endpoints for technical service

### PR DESCRIPTION
**Pull request by cworf91**
**Changes in this Pull Request:**
- add get xml endpoints for technical service
- add getCollection xml endpoints for technical service

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](<enter URL to a job here>)
- [OSCM Pull And Start job](<enter URL to a job here>)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @cworf91 and @GoebelL)

___
*[oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java, line 124 at r1](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249#-MKKrMqv2A1H5T4YjvcI:-MKKPTH_-u30nRfN9gb7:b-9at8xi) ([raw file](https://github.com/servicecatalog/oscm-rest-api/blob/c83b8c18026df29e55fc1899a15960d7c9c26ca3/oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java#L124)):*
> ```Java
>   @Since(CommonParams.VERSION_1)
>   @Path(CommonParams.PATH_ID + "/xml")
>   @Produces(MediaType.APPLICATION_XML)
> ```

I am not happy to have such duplication on the API. Instead of two endpoints with different paths, we should have a single endpoint that serves for both formats as also described in the feature request.
 
This can be achieved for example by using the Accept request header field. See [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1) for definition details.
The endpoint implementation shall evaluate this header and dynamically chose the requested response format. Swagger documentation for the output format is minor and I strongly believe solvable with alternative means than with this '@ApiResponse @Content' annotation.

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @content)

___
*[oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java, line 124 at r1](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249#-MKKrMqv2A1H5T4YjvcI:-MKj70WI5Q7hgl0pzNaI:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-rest-api/blob/c83b8c18026df29e55fc1899a15960d7c9c26ca3/oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java#L124)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

I am not happy to have such duplication on the API. Instead of two endpoints with different paths, we should have a single endpoint that serves for both formats as also described in the feature request.
 
This can be achieved for example by using the Accept request header field. See (RFC 2616)[https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1] for definition details.
The endpoint implementation shall evaluate this header and dynamically chose the requested response format. Swagger documentation for the output format is minor and I strongly believe solvable with alternative means than with this '@ApiResponse @Content' annotation.
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249)* status: 2 of 4 files reviewed, all discussions resolved

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249)* status: 3 of 4 files reviewed, all discussions resolved

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java, line 87 at r2](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249#-ML9Ye8w9AJY7JyjMXhl:-ML9Ye8w9AJY7JyjMXhm:bo8ktv8) ([raw file](https://github.com/servicecatalog/oscm-rest-api/blob/8e3c2049fe9c831137ff8e91eb27603c2c127d93/oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java#L87)):*
> ```Java
>       throws Exception {
>     if (headers.getMediaType() != null
>         && headers.getMediaType().toString().equals(MediaType.APPLICATION_XML)) {
> ```

Small code style improvement: If not using Optionals here, at least turn the condition vice versa to have it better readable. 

```
   if (MediaType.APPLICATION_XML.equals(headers.getMediaType())) {
   ...
```
Should be sufficient :-)

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java, line 87 at r2](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249#-ML9Ye8w9AJY7JyjMXhl:-ML9_fsIEAAVNQrG7OeC:b6cl7pn) ([raw file](https://github.com/servicecatalog/oscm-rest-api/blob/8e3c2049fe9c831137ff8e91eb27603c2c127d93/oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java#L87)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Small code style improvement: If not using Optionals here, at least turn the condition vice versa to have it better readable. 

```
   if (MediaType.APPLICATION_XML.equals(headers.getMediaType())) {
   ...
```
Should be sufficient :-)

</blockquote></details>

Tip: With static import of MediaType.APPLICATION_XML you make it yet nicely shorter.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @cworf91)

___
*[oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java, line 125 at r2](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249#-ML9b51tBT5oXiZDr4Y5:-ML9b51tBT5oXiZDr4Y6:bb7eybp) ([raw file](https://github.com/servicecatalog/oscm-rest-api/blob/8e3c2049fe9c831137ff8e91eb27603c2c127d93/oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java#L125)):*
> ```Java
>     if (headers.getMediaType() != null
>         && headers.getMediaType().toString().equals(MediaType.APPLICATION_XML)) {
>       return tsb.getXMLCollection();
> ```

dito

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java, line 125 at r2](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249#-ML9b51tBT5oXiZDr4Y5:-MLCHgOLBka2H-pun-rO:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-rest-api/blob/8e3c2049fe9c831137ff8e91eb27603c2c127d93/oscm-rest-api-service/src/main/java/org/oscm/rest/service/TechnicalServiceResource.java#L125)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-rest-api/249)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
