### PR TITLE
Fb mavenize

### PR DESCRIPTION
**Pull request by skulle**
first versions of mavenized projects

### CODE REVIEW

**Comment by DawidCh** [comment]
If you use dependency as follows:
```
<dependency>
			<groupId>com.github.servicecatalog</groupId>
			<artifactId>oscm-commons</artifactId>
			<version>1.1</version>
</dependency>
```
you are attaching whole oscm-commons as dependency (with all it's dependencies)
try following:
```
<dependency>
        <groupId>com.github.servicecatalog.oscm-commons</groupId>
        <artifactId>oscm-common</artifactId>
        <version>1.2</version>
      </dependency>
```
I have following remarks:
1. Could you please bind all the oscm-rest* modules with one parent pom.xml and use dependencyManagement for managing libraries?
2. We are using ```<groupId>org.oscm</groupId>``` and ```<groupId>org.oscm.app</groupId>``` as groups id. Could you please use ```<groupId>org.oscm.rest</groupId>```?
3. Could you please rename the artifactids according to pattern oscm-**?
4. Could you please provide travisCi configuration?

**Comment by skulle** [comment]
- groupId and artifact names are fixed, also narrowed down the dependencies.
- Are you sure about the parent pom for all api projects? Thought they are more independent projects not contributing to a common artifact.
- I have no clue about configuring travis ci. Probably it makes more sense if someone else takes this over? Of course i can have a look if you want.

**Comment by DawidCh** [comment]
> groupId and artifact names are fixed, also narrowed down the dependencies.

Thanks.
> I have no clue about configuring travis ci. Probably it makes more sense if someone else takes this over? Of course i can have a look if you want.

Done.
> Are you sure about the parent pom for all api projects? Thought they are more independent projects not contributing to a common artifact.

Yes. As a developer I (usually) expect following procedure, while starting to work with new repository:
```
git clone http://...
mvn clean install (in root folder of repository)
```
If they are independent projects and it is required to treat them as independent projects, then I would advise to use separate repository for each project.

**Comment by skulle** [comment]
ok i think everything is refactored now

**Comment by DawidCh** [comment]
;)

**Pull request merged**
